# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('gps', models.CharField(max_length=255)),
                ('aid', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('pests', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('elevation', models.CharField(max_length=255)),
                ('windspeed', models.CharField(max_length=255)),
                ('winddir', models.CharField(max_length=255)),
                ('temp', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('rain', models.CharField(max_length=255)),
                ('clouds', models.CharField(max_length=255)),
            ],
        ),
    ]
