# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160328_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fia',
            name='phone',
            field=models.CharField(blank=True, default='unable to collect phone', max_length=255),
        ),
    ]
