# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160328_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fia',
            name='clouds',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='elevation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='humidity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='rain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='temp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='winddir',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fia',
            name='windspeed',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
