# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160328_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fia',
            name='clouds',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='elevation',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='humidity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='rain',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='temp',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='winddir',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fia',
            name='windspeed',
            field=models.FloatField(blank=True),
        ),
    ]
