# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160408_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fia',
            name='owner',
        ),
    ]
