# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_fia_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_variable', models.CharField(max_length=255)),
                ('logic_operator', models.CharField(max_length=255)),
                ('recipe_limit', models.PositiveIntegerField()),
                ('recipe_range', models.PositiveIntegerField()),
                ('multiple', models.CharField(max_length=255)),
                ('recipe_match', models.CharField(max_length=255)),
                ('recipe_alert', models.CharField(max_length=255)),
                ('recipe_name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
