# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_variable', models.CharField(max_length=40)),
                ('logic_operator', models.NullBooleanField()),
                ('recipe_limit', models.PositiveIntegerField()),
                ('recipe_range', models.PositiveIntegerField()),
            ],
        ),
    ]
