# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_recipe_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='multiple',
            field=models.CharField(max_length=40),
        ),
    ]
