# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160324_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_match',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
