# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_recipe_recipe_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_alert',
            field=models.CharField(default='scout', max_length=40),
            preserve_default=False,
        ),
    ]
