# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_recipe_recipe_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Recipe', max_length=40),
            preserve_default=False,
        ),
    ]
