# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_recipe_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
    ]
